Update script

diff --git a/script b/script
--- a/script
+++ b/script
@@ -142,3 +142,114 @@ do
    fi
 done
 echo "maximum element is $max"
+
+//bill calc
+calculate_bill()
+{
+   local units=$1
+   local bill=0
+
+   local rate1=1.50
+   local rate2=3.00
+   local rate3=4.50
+   local rate4=6.00
+
+   if [ $units -le 50 ]; then
+	bill=$(echo "$units * $rate1" | bc)
+   elif [ $units -le 150 ]; then
+	bill=$(echo "50 * $rate1 + ($units-50) * $rate2" | bc)
+   elif [ $units -le 250 ]; then
+	bill=$(echo "50 * $rate1 + 100 * $rate2 + ($units - 150) * $rate3" | bc)
+   else
+	bill=$(echo "50 * $rate1 + 100 * $rate2 + 150 * $rate3 + ($units-200) * $rate4" | bc)
+   fi
+echo "total electricity bill for $units units: $bill"
+}
+echo "enter number of units consumed:" 
+read units
+if ! [[ $units =~ ^[0-9]+$ ]]; then
+  echo "please enter a valid number of units:"
+  exit 1
+fi
+calculate_bill $units
+   
+
+//grade
+calculate_grade()
+{
+  local average=$1
+  local grade=""
+  if (( $(echo "$average >= 90" | bc -l) )); then
+	grade="A"
+  elif (( $(echo "$average >= 80" | bc -l) )); then
+        grade="B"
+  elif (( $(echo "$average >= 70" | bc -l) )); then
+	grade="C"
+  elif (( $(echo "$average >= 60" | bc -l) )); then
+	grade="D"
+  else
+        grade="F"
+  fi
+
+  echo $grade
+}
+
+echo "enter marks for subj1:"
+read sub1
+echo "enter marks for subj2:"
+read sub2
+echo "enter marks for subj3:"
+read sub3
+echo "enter marks for subj4:"
+read sub4
+echo "enter marks for subj5:"
+read sub5
+if ! [[ $sub1 =~ ^[0-9]+$ && $sub2 =~ ^[0-9]+$ && $sub3 =~ ^[0-9]+$ && $sub4 =~ ^[0-9]+$ && $sub5 =~ ^[0-9]+$ ]]; then
+echo "please enter a valid number"
+exit 1
+fi
+
+total=$(echo "$sub1 + $sub2 + $sub3 + $sub4 + $sub5" | bc)
+average=$(echo "$total / 5" | bc -l)
+grade=$(calculate_grade $average)
+
+echo "total marks: $total"
+echo "average marks is $average"
+echo "grade is $grade"
+
+//multiplication table
+echo "enter a number"
+read n
+for((i=1;i<=10;i++));
+do
+echo "$n * $i = $((n*i))"
+done
+
+//word count
+echo "enter a sentence:"
+read sent
+word=($sent)
+echo "number of words: ${#word[@]}"
+echo "words:"
+for word in "${word[@]}"; do
+    echo "$word"
+done
+
+//no: of words in a file
+echo "enter filename:"
+read file
+if [ -f "$file" ]; then
+   words=$(wc -w < "$file")
+   echo "file is $file and no: of words is $words"
+else
+   echo "error"
+fi
+
+
+//file count
+echo "file count"
+dir=$(pwd)
+file_count=$(ls -l $dir | wc -l)
+echo "$file_count"
+
+//
